"""
Ad Consultant campaign generator — takes the wizard's answers (goal, budget, location,
keyword direction, landing page choice) and produces a complete, reviewable campaign
package via Claude: keywords, RSA headlines/descriptions, budget breakdown, targeting,
and a landing page (either a pick from the real site, or a content brief for Jordan's
separate landing-page-generating tool).

Nothing here ever touches the live Google Ads account — it only creates a CampaignPackage
row for human review, same as every other AI-generated recommendation in this app.

Implementation instructions are NOT generated by Claude — the mechanics of "how to create
a campaign in the Google Ads UI" don't change per campaign, so they're a fixed template
(STEP_DEFS below) with the AI-generated content (budget/targeting/keywords/copy/landing
page) slotted in at the steps that actually need it. This is more reliable than asking
Claude to reinvent UI navigation each time, and keeps each step focused on one thing
instead of dumping everything on one page.

Runs in a background thread (same pattern as engines/ads_analyzer.py) rather than
synchronously in the request — this is a large structured-JSON generation that can
occasionally run past gunicorn's worker timeout, which kills the connection before Flask
can respond. The wizard starts generation and polls /api/consultant/status instead.
"""

import json
import logging
import threading

import config
from engines import claude_client
from engines.ads_skills import base as skills_base

logger = logging.getLogger(__name__)

# Known static marketing pages on archangeltrust.com (not tracked in WebflowPost, which
# only covers the Blog Posts CMS collection) — gives the model real candidates to suggest
# from instead of inventing a URL, when the client picks an existing page.
KNOWN_SITE_PAGES = [
    "Home (archangeltrust.com/)",
    "Apple Valley Estate Planning Attorney (/apple-valley-estate-planning-attorney)",
    "San Diego / California Estate Planning (/california-estate-planning)",
    "Estate Planning Services (/estate-planning-services)",
    "Probate (/probate)",
    "Advanced Planning & Special Needs Trusts (/advanced-planning)",
    "Attorney Profile (/attorney-profile-estate-planning-attorney-near-me)",
    "Contact (/contact)",
]

GOAL_LABELS = {
    "more_consultations": "Drive more consultation bookings",
    "brand_awareness": "Build brand awareness in a new area",
    "specific_service": "Promote a specific service",
    "other": "Other (see notes)",
}


def _system_prompt(landing_page_mode):
    landing_instruction = (
        '- "landing_page_suggestion": which existing page to send traffic to and why (pick from the provided list)'
        if landing_page_mode == "existing" else
        '- "landing_page_prompt": a content/design brief for a NEW landing page — headline direction, '
        "the 3-4 key points it should cover, the offer/CTA, and tone. Written so it can be handed directly "
        "to a separate landing-page-generating tool, not for a human reading Google Ads instructions."
    )
    return f"""You are a Google Ads consultant building a new campaign proposal for Archangel \
Trust, a California estate planning and probate law firm (San Diego and Apple Valley). \
You're given the client's goal, budget, target location, and keyword direction — produce a \
complete, ready-to-review campaign package.

If the requested location conflicts with the business rules below (e.g. San Diego is \
currently paused), still produce the package but say so plainly in the summary — don't \
silently ignore the conflict or silently refuse.

Write for someone who is not a marketer and doesn't know Google Ads jargon. Keep the summary \
short and plain.

Return a JSON object with exactly these fields:
- "campaign_name": short descriptive name (e.g. "AV - Living Trusts - Search")
- "summary": 2 plain-English sentences — what this campaign is and any conflict/caveat worth flagging. No jargon.
- "keywords": array of 10-15 objects {{"keyword": "...", "match_type": "Phrase"|"Exact"|"Broad"}}
- "headlines": array of 8-10 RSA headlines, each under 30 characters
- "descriptions": array of 3-4 RSA descriptions, each under 90 characters
- "budget_breakdown": 1 sentence on daily budget and pacing — plain language, no jargon
- "targeting": 1 sentence on geographic/demographic targeting — plain language
{landing_instruction}

Return only the JSON object, no other text."""


def _build_prompt(goal, goal_freeform, budget_monthly, location, keyword_direction,
                   landing_page_mode, landing_page_preference):
    rules = skills_base.business_rules_block()
    target = skills_base.monthly_target()

    lines = [
        rules,
        "",
        "## Campaign Request",
        f"- Goal: {GOAL_LABELS.get(goal, goal)}",
    ]
    if goal_freeform:
        lines.append(f"- Additional notes on goal: {goal_freeform}")
    lines.append(f"- Monthly budget: ${budget_monthly:.0f}")
    lines.append(f"- Location: {location}")
    if keyword_direction:
        lines.append(f"- Keyword direction from client: {keyword_direction}")
    else:
        lines.append("- No specific keyword direction given — suggest based on the goal and business rules.")

    if landing_page_mode == "existing":
        if landing_page_preference:
            lines.append(f"- Landing page preference from client: {landing_page_preference}")
        lines.append("\n## Known site pages (pick from these for the landing page suggestion)")
        for p in KNOWN_SITE_PAGES:
            lines.append(f"- {p}")
    else:
        lines.append("- Client wants a NEW custom landing page built for this campaign "
                      "(via a separate tool) instead of using an existing page.")
        if landing_page_preference:
            lines.append(f"- Client's notes on what the new page should include: {landing_page_preference}")

    lines.append(f"\nMonthly booking goal: {target['bookings']}, target CPA: under ${target['cpa_max']}.")

    return "\n".join(lines)


def _as_text(value):
    """Claude sometimes returns a text field as a list of strings/steps instead of one
    string despite the prompt asking for a string — normalize either shape to text."""
    if isinstance(value, list):
        return "\n".join(str(v) for v in value)
    return value or ""


def _generate_sync(app, goal, goal_freeform, budget_monthly, location, keyword_direction,
                    landing_page_mode, landing_page_preference):
    """Do the actual generation + persistence. Returns (package_id, error_msg)."""
    if not config.ANTHROPIC_API_KEY:
        return None, "ANTHROPIC_API_KEY not configured"

    with app.app_context():
        from models import db, CampaignPackage

        prompt = _build_prompt(goal, goal_freeform, budget_monthly, location, keyword_direction,
                                landing_page_mode, landing_page_preference)
        system_prompt = _system_prompt(landing_page_mode)

        try:
            result = claude_client.call_json(system_prompt, prompt, max_tokens=3072, cache_system=False)
        except Exception as e:
            logger.error(f"Campaign builder failed: {e}")
            return None, str(e)

        pkg = CampaignPackage(
            goal=goal,
            goal_freeform=goal_freeform,
            budget_monthly=budget_monthly,
            location=location,
            keyword_direction=keyword_direction,
            landing_page_mode=landing_page_mode,
            landing_page_preference=landing_page_preference,
            campaign_name=_as_text(result.get("campaign_name", "New Campaign")),
            summary=_as_text(result.get("summary", "")),
            keywords_json=json.dumps(result.get("keywords", [])),
            headlines_json=json.dumps(result.get("headlines", [])),
            descriptions_json=json.dumps(result.get("descriptions", [])),
            budget_breakdown=_as_text(result.get("budget_breakdown", "")),
            targeting=_as_text(result.get("targeting", "")),
            landing_page_suggestion=_as_text(result.get("landing_page_suggestion", "")),
            landing_page_prompt=_as_text(result.get("landing_page_prompt", "")) or None,
        )
        db.session.add(pkg)
        db.session.commit()
        return pkg.id, None


_lock = threading.Lock()
_running = False
_last_result = {"id": None, "error": None}


def generate_background(app, goal, goal_freeform, budget_monthly, location, keyword_direction,
                         landing_page_mode, landing_page_preference):
    """Spawn a background thread to generate the package. Returns False if one's already running."""
    global _running
    if not _lock.acquire(blocking=False):
        return False
    _running = True
    _last_result["id"] = None
    _last_result["error"] = None

    def _worker():
        global _running
        try:
            pkg_id, error = _generate_sync(
                app, goal, goal_freeform, budget_monthly, location, keyword_direction,
                landing_page_mode, landing_page_preference,
            )
            _last_result["id"] = pkg_id
            _last_result["error"] = error
        finally:
            _running = False
            _lock.release()

    threading.Thread(target=_worker, daemon=True).start()
    return True


def is_running():
    return _running


def get_last_result():
    return dict(_last_result)


# ── Fixed implementation-step template ──────────────────────────────────────────
# Not AI-generated — the Google Ads UI mechanics are the same for every campaign, only
# the content differs. Each step is one of:
#   kind "text"      — static or lightly-templated copy, shown as-is
#   kind "keywords"  — renders pkg's keyword list
#   kind "ad_copy"   — renders pkg's headlines/descriptions
#   kind "landing"   — renders the existing-page suggestion or the custom-page prompt

def get_steps(pkg):
    keywords = json.loads(pkg.keywords_json or "[]")
    headlines = json.loads(pkg.headlines_json or "[]")
    descriptions = json.loads(pkg.descriptions_json or "[]")

    steps = [
        {
            "title": "Create the campaign",
            "kind": "text",
            "body": "In Google Ads, click <strong>+ New Campaign</strong> in the left sidebar.",
        },
        {
            "title": "Choose your goal & campaign type",
            "kind": "text",
            "body": f"Select <strong>Leads</strong> as the objective, then <strong>Search</strong> as the campaign type. "
                    f"({GOAL_LABELS.get(pkg.goal, pkg.goal)})",
        },
        {
            "title": "Set your budget",
            "kind": "text",
            "body": pkg.budget_breakdown or f"Set the daily budget from your ${pkg.budget_monthly:.0f}/month total.",
        },
        {
            "title": "Set targeting",
            "kind": "text",
            "body": pkg.targeting or "Set location and audience targeting.",
        },
        {
            "title": "Add your keywords",
            "kind": "keywords",
            "keywords": keywords,
        },
        {
            "title": "Write your ads",
            "kind": "ad_copy",
            "headlines": headlines,
            "descriptions": descriptions,
        },
        {
            "title": "Set up the landing page",
            "kind": "landing",
            "mode": pkg.landing_page_mode,
            "suggestion": pkg.landing_page_suggestion,
            "prompt": pkg.landing_page_prompt,
        },
        {
            "title": "Review & launch",
            "kind": "text",
            "body": "Double check everything, then click <strong>Save and Continue</strong>. Google typically "
                    "reviews new campaigns within one business day before ads start showing.",
        },
    ]
    return steps
