"""WoW/MoM performance deltas. Deterministic (no LLM call) — this is arithmetic over
existing snapshots, not analysis; only surfaces a recommendation when a move is large
enough to be worth a human's attention. Complements (doesn't replace) the full-text
weekly summary generated by engines/weekly_summary.py."""

from datetime import date, timedelta

from models import db, GoogleAdsSnapshot

SKILL_ID = "weekly_digest"

MOVE_THRESHOLD_PCT = 20  # only surface deltas at least this large


def _pct_change(new, old):
    if not old:
        return None
    return round(100 * (new - old) / old, 1)


def run():
    since = date.today() - timedelta(days=60)
    snapshots = (
        db.session.query(GoogleAdsSnapshot)
        .filter(GoogleAdsSnapshot.snapshot_date >= since)
        .order_by(GoogleAdsSnapshot.snapshot_date.desc())
        .limit(2)
        .all()
    )
    if len(snapshots) < 2:
        return []

    latest, prior = snapshots[0], snapshots[1]
    items = []
    for name, new, old, unit in [
        ("spend", latest.total_spend, prior.total_spend, "$"),
        ("conversions", latest.total_conversions, prior.total_conversions, ""),
        ("CPA", latest.cpa, prior.cpa, "$"),
    ]:
        delta = _pct_change(new, old)
        if delta is None or abs(delta) < MOVE_THRESHOLD_PCT:
            continue
        direction = "up" if delta > 0 else "down"
        items.append({
            "category": "alerts",
            "priority": "high" if abs(delta) >= 40 else "medium",
            "title": f"{name} {direction} {abs(delta):.0f}% period-over-period",
            "recommendation": f"Review the {name} trend on /paid-ads — moved from "
                               f"{unit}{old:.2f} to {unit}{new:.2f}.",
            "rationale": f"Period-over-period {name} change of {delta:+.1f}% "
                         f"({prior.period_end or prior.snapshot_date} snapshot vs. "
                         f"{latest.period_end or latest.snapshot_date} snapshot).",
        })
    return items
